
```{r setup, echo=FALSE}
library(ggplot2)
library(ggrepel)

```

### NEON VST Mapper
### `r paste0("Plot Map: ", input$plotSelect)`
```{r downloadPlotMap, echo=FALSE, fig.align='left', fig.height=9, warning=FALSE}

##  Build the ggplot object for download and printing
ggDownload <- ggplot(mapPoints(), aes(pointeasting, pointnorthing)) +
  # Set the aspect ratio using the mapPoint data
  coord_fixed() +
      
  # Add title, axis labels, and caption to hold nestedSubplotSize data
  labs(x = "Easting (meters)",
       y = "Northing (meters)",
       caption = captionInput()) +
      
  # Remove axis and grid lines from panel, place legend at bottom, and size text output for printing/download
  theme(panel.grid = element_blank()) +
  theme(axis.text = element_text(size = 8)) +
  theme(axis.title = element_text(size = 9, face = "bold")) +
  theme(legend.text = element_text(size=7)) +
  
  # Set axis ticks to begin at minimum easting and northing values in mapPoints, and space every 5 meters
  scale_x_continuous(breaks=seq(round(min(mapPoints()$pointeasting)), max(mapPoints()$pointeasting),5)) +
  scale_y_continuous(breaks=seq(round(min(mapPoints()$pointnorthing)), max(mapPoints()$pointnorthing),5)) +
  
  # Rotate y-axis labels 90-degrees
  theme(axis.text.y  = element_text(angle=90, hjust=0.5)) +
      
  # Draw perimeter of plot/subplot
  geom_segment(x = E1(), y = N1(), xend = E2(), yend = N2(), color = "grey30") +
  geom_segment(x = E2(), y = N2(), xend = E4(), yend = N4(), color = "grey30") +
  geom_segment(x = E1(), y = N1(), xend = E3(), yend = N3(), color = "grey30") +
  geom_segment(x = E3(), y = N3(), xend = E4(), yend = N4(), color = "grey30") +
      
  # Add corner points (and centroid if present) using high-res GPS data
  geom_point(size=2, shape=21, colour="black", fill="red", stroke=1, show.legend = FALSE)


##  Add layers based on user input
if (input$radio=="color") ggDownload = ggDownload + 
  geom_point(data = mapData(), aes(x = stemeasting, y = stemnorthing, color = taxonid), size = 2, shape = 21, stroke = 0.5, show.legend = TRUE)

if (input$radio=="shape") ggDownload = ggDownload +
  geom_point(data = mapData(), aes(x = stemeasting, y = stemnorthing, shape = taxonid), size = 2, stroke = 0.5, show.legend = TRUE) +
        scale_shape_discrete(solid = FALSE)

if ("tags" %in% input$checkGroup) ggDownload = ggDownload + 
  geom_text_repel(data=mapData(), aes(x=stemeasting, y=stemnorthing, label=tagid), size=2, nudge_x = 0.3, nudge_y = 0.3)

if ("markers" %in% input$checkGroup) ggDownload = ggDownload + geom_label(aes(label = pointid), fill = "#FF6C5E", size=2, show.legend = FALSE)

ggDownload

```